version: '3.9'

services:
    neo4j:
        image: neo4j
        restart: unless-stopped
        environment:
            - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
            - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
        volumes:
            - neo4j_data:/data
            - neo4j_logs:/logs
            - neo4j_import:/var/lib/neo4j/import
            - neo4j_plugins:/plugins
    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
            - postgres_logs:/logs
    app:
        build: .
        # image: cyclepath
        restart: unless-stopped
        depends_on:
            - neo4j
            - postgres
        ports:
            - '5000:80'
        environment:
            - BASE_URL=/api
            - AIR_QUALITY_KEY=${AIR_QUALITY_KEY}
            - MAPS_KEY=${MAPS_KEY}

            - NEO4J_SCHEME=bolt
            - NEO4J_HOST=neo4j
            - NEO4J_PORT=7687
            - NEO4J_USERNAME=${NEO4J_USERNAME}
            - NEO4J_PASSWORD=${NEO4J_PASSWORD}

            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_DB=${PG_DB}

volumes:
    postgres_data:
    postgres_logs:
    neo4j_data:
    neo4j_logs:
    neo4j_import:
    neo4j_plugins:
