version: '3.1'

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres_cyclepath
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - data:/var/lib/postgresql/data/pgdata
            - logs:/logs

volumes:
    data:
    logs:
