version: '3.9'

services:
    neo4j:
        image: neo4j:latest
        container_name: neo4j-cyclepath
        restart: always
        ports:
            - '7474:7474'
            - '7687:7687'
        environment:
            - NEO4J_AUTH=${CON_USER}/${CON_PASS}
            - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
        volumes:
            - $HOME/docker/neo4j/data:/data
            - $HOME/docker/neo4j/logs:/logs
            - $HOME/docker/neo4j/import:/var/lib/neo4j/import
            - $HOME/docker/neo4j/plugins:/plugins

volumes:
    data:
    logs:
    import:
    plugins:
