version: '3.8'

services:
    neo4j:
        image: neo4j:latest
        container_name: neo4j-cyclepath
        restart: always
        ports:
            - '7687:7687'
        environment:
            - NEO4J_AUTH=${CON_USER}/${CON_PASS}
            - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
        volumes:
            - data:/data
            - logs:/logs
            - import:/var/lib/neo4j/import
            - plugins:/plugins

volumes:
    data:
    logs:
    import:
    plugins:
