version: "3.9"

services:
    neo4j:
        image: neo4j:latest
        restart: always
        ports:
            - '7474:7474'
            - '7687:7687'
        environment:
            - NEO4J_dbms_memory_heap_maxSize=2G
            - NEO4JLABS_PLUGINS='["graph-data-science"]'
            - NEO4J_AUTH=${CON_USER}/${CON_PASS}
