version: '3.9'

services:
    neo4j:
        image: neo4j:latest
        restart: always
        container_name: neo4j-cyclepath
        ports:
            - '7474:7474'
            - '7687:7687'
        environment:
            - NEO4J_AUTH=${CON_USER}/${CON_PASS}
            - NEO4J_dbms_memory_heap_maxSize=2G
            - NEO4JLABS_PLUGINS='["graph-data-science", "apoc"]'
        volumes:
            - data:/data
            - logs:/logs
            - import:/var/lib/neo4j/import
            - plugins:/plugins

volumes:
    data:
    logs:
    import:
    plugins:
