name: hacktues
channels:
    - conda-forge
    - defaults
dependencies:
    - argh=0.26.2
    - black==20.8b1
    - pip=21.0.1
    - python=3.9.2
    - tqdm=4.59.0
    - pip:
          - osmium==3.1.3
          - py2neo==2021.0.1
          - python-dotenv==0.17.0
