version: '3.9'

services:
    neo4j:
        image: neo4j
        restart: always
        ports:
            - '7687:7687'
        environment:
            - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
            - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
        volumes:
            - neo4j_data:/data
            - neo4j_logs:/logs
            - neo4j_import:/var/lib/neo4j/import
            - neo4j_plugins:/plugins
    postgres:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata
            - postgres_logs:/logs

volumes:
    postgres_data:
    postgres_logs:
    neo4j_data:
    neo4j_logs:
    neo4j_import:
    neo4j_plugins:
